import type { LucideIcon } from "lucide-react";
import {
  Building2,
  Users,
  Bell,
  FolderOpen,
  FileBarChart2,
  Receipt,
  CreditCard,
  Eye,
  Wallet,
  FileSpreadsheet,
  MessageSquareWarning,
  Wrench,
  Boxes,
  Truck,
  KanbanSquare,
  Package,
  UserCheck,
  DoorOpen,
  ParkingSquare,
  ShieldCheck,
  UserX,
  Megaphone,
  MessagesSquare,
  Vote,
  CalendarDays,
  Dumbbell,
  Landmark,
  Gauge,
  Sparkles,
  Settings,
  Shield,
  FileText,
  Home,
  BarChart3,
} from "lucide-react";

export type ModuleCategory =
  "Core" | "Finance" | "Operations" | "Security" | "Community" | "Utilities" | "Intelligence";

export interface ModuleDef {
  key: string;
  name: string;
  category: ModuleCategory;
  icon: LucideIcon;
  description: string;
  plan: "Core" | "Starter" | "Growth" | "Professional" | "Enterprise";
  /** Optional dedicated route — if absent, falls back to /modules/:key */
  route?: string;
}

/** Modules that have their own dedicated page routes */
export const DEDICATED_ROUTES: Record<string, string> = {
  platform: "/platform",
  property: "/property",
  residents: "/residents",
  notifications: "/notifications",
  documents: "/documents",
  reports: "/reports",
  ledger: "/ledger",
  payments: "/payments",
  financial_transparency: "/financial-transparency",
  budget: "/budget",
  complaints: "/complaints",
  maintenance: "/maintenance",
  vendors: "/vendors",
  vendor_finance: "/vendor-finance",
  inventory: "/inventory",
  projects: "/projects",
  assets: "/assets",
  visitor: "/visitor",
  gate: "/security",
  guard_patrol: "/security",
  blacklist: "/security",
  parking: "/parking",
  utility_meters: "/utility-meters",
  notice_board: "/notices",
  community_forum: "/forum",
  polls: "/polls",
  events: "/events",
  amenities: "/amenities",
  governance: "/governance",
  ai_maintenance: "/ai-maintenance",
};

export const MODULES: ModuleDef[] = [
  // Core
  {
    key: "platform",
    name: "Platform Core",
    category: "Core",
    icon: Shield,
    description: "Auth, RBAC, tenants, audit logs",
    plan: "Core",
    route: "/platform",
  },
  {
    key: "property",
    name: "Property",
    category: "Core",
    icon: Building2,
    description: "Society, blocks, floors, units",
    plan: "Core",
    route: "/property",
  },
  {
    key: "residents",
    name: "Residents",
    category: "Core",
    icon: Users,
    description: "Resident profiles, occupancy",
    plan: "Core",
    route: "/residents",
  },
  {
    key: "notifications",
    name: "Notifications",
    category: "Core",
    icon: Bell,
    description: "Email, SMS, push, WhatsApp",
    plan: "Core",
    route: "/notifications",
  },
  {
    key: "documents",
    name: "Documents",
    category: "Core",
    icon: FolderOpen,
    description: "Storage, versions, access control",
    plan: "Core",
    route: "/documents",
  },
  {
    key: "reports",
    name: "Reports",
    category: "Core",
    icon: FileBarChart2,
    description: "PDF & Excel reporting engine",
    plan: "Core",
    route: "/reports",
  },
  // Finance
  {
    key: "ledger",
    name: "Ledger",
    category: "Finance",
    icon: Receipt,
    description: "Per-unit ledger & charges",
    plan: "Starter",
    route: "/ledger",
  },
  {
    key: "payments",
    name: "Payments",
    category: "Finance",
    icon: CreditCard,
    description: "Receipts and allocation",
    plan: "Starter",
    route: "/payments",
  },
  {
    key: "financial_transparency",
    name: "Transparency",
    category: "Finance",
    icon: Eye,
    description: "Public income & expense statements",
    plan: "Growth",
    route: "/financial-transparency",
  },
  {
    key: "budget",
    name: "Budget",
    category: "Finance",
    icon: Wallet,
    description: "Annual budgets & variance",
    plan: "Growth",
    route: "/budget",
  },
  {
    key: "vendor_finance",
    name: "Vendor Finance",
    category: "Finance",
    icon: FileSpreadsheet,
    description: "PO, invoice, vendor payments",
    plan: "Growth",
    route: "/vendor-finance",
  },
  // Operations
  {
    key: "complaints",
    name: "Complaints",
    category: "Operations",
    icon: MessageSquareWarning,
    description: "Submit, assign, resolve",
    plan: "Starter",
    route: "/complaints",
  },
  {
    key: "maintenance",
    name: "Maintenance",
    category: "Operations",
    icon: Wrench,
    description: "Schedules & work orders",
    plan: "Growth",
    route: "/maintenance",
  },
  {
    key: "inventory",
    name: "Inventory",
    category: "Operations",
    icon: Boxes,
    description: "Spare parts \u0026 stock",
    plan: "Growth",
    route: "/inventory",
  },
  {
    key: "vendors",
    name: "Vendors",
    category: "Operations",
    icon: Truck,
    description: "Vendor registry & RFQs",
    plan: "Growth",
    route: "/vendors",
  },
  {
    key: "projects",
    name: "Projects",
    category: "Operations",
    icon: KanbanSquare,
    description: "Plans, milestones, expenses",
    plan: "Professional",
    route: "/projects",
  },
  {
    key: "assets",
    name: "Assets",
    category: "Operations",
    icon: Package,
    description: "Asset register & AMC",
    plan: "Growth",
    route: "/assets",
  },
  // Security
  {
    key: "visitor",
    name: "Visitors",
    category: "Security",
    icon: UserCheck,
    description: "Pre-register & QR passes",
    plan: "Growth",
    route: "/visitor",
  },
  {
    key: "gate",
    name: "Gate",
    category: "Security",
    icon: DoorOpen,
    description: "Entry/exit logs",
    plan: "Growth",
    route: "/security",
  },
  {
    key: "parking",
    name: "Parking",
    category: "Security",
    icon: ParkingSquare,
    description: "Slot allocation & bookings",
    plan: "Growth",
    route: "/parking",
  },
  {
    key: "guard_patrol",
    name: "Guard Patrol",
    category: "Security",
    icon: ShieldCheck,
    description: "Shifts, patrols, incidents",
    plan: "Professional",
    route: "/security",
  },
  {
    key: "blacklist",
    name: "Blacklist",
    category: "Security",
    icon: UserX,
    description: "Restricted visitors / vehicles",
    plan: "Growth",
    route: "/security",
  },
  // Community
  {
    key: "notice_board",
    name: "Notice Board",
    category: "Community",
    icon: Megaphone,
    description: "Society announcements",
    plan: "Starter",
    route: "/notices",
  },
  {
    key: "community_forum",
    name: "Forum",
    category: "Community",
    icon: MessagesSquare,
    description: "Resident discussions",
    plan: "Growth",
    route: "/forum",
  },
  {
    key: "polls",
    name: "Polls",
    category: "Community",
    icon: Vote,
    description: "Polls & AGM voting",
    plan: "Professional",
    route: "/polls",
  },
  {
    key: "events",
    name: "Events",
    category: "Community",
    icon: CalendarDays,
    description: "Society events calendar",
    plan: "Growth",
    route: "/events",
  },
  {
    key: "amenities",
    name: "Amenities",
    category: "Community",
    icon: Dumbbell,
    description: "Gym, hall, pool bookings",
    plan: "Professional",
    route: "/amenities",
  },
  {
    key: "governance",
    name: "Governance",
    category: "Community",
    icon: Landmark,
    description: "Committee, AGM, resolutions",
    plan: "Professional",
    route: "/governance",
  },
  // Utilities
  {
    key: "utility_meters",
    name: "Utility Meters",
    category: "Utilities",
    icon: Gauge,
    description: "Meter readings & charges",
    plan: "Growth",
    route: "/utility-meters",
  },
  // Intelligence
  {
    key: "ai_complaints",
    name: "AI Complaints",
    category: "Intelligence",
    icon: Sparkles,
    description: "Auto-categorize & prioritize",
    plan: "Professional",
  },
  {
    key: "ai_finance",
    name: "AI Finance",
    category: "Intelligence",
    icon: Sparkles,
    description: "Anomaly & forecast",
    plan: "Professional",
  },
  {
    key: "ai_maintenance",
    name: "AI Maintenance",
    category: "Intelligence",
    icon: Sparkles,
    description: "Failure prediction",
    plan: "Professional",
    route: "/ai-maintenance",
  },
];

export const CATEGORY_ORDER: ModuleCategory[] = [
  "Core",
  "Finance",
  "Operations",
  "Security",
  "Community",
  "Utilities",
  "Intelligence",
];

export const PRIMARY_NAV: {
  to: string;
  label: string;
  icon: LucideIcon;
  superAdminOnly?: boolean;
}[] = [
  { to: "/", label: "Dashboard", icon: Home },
  { to: "/societies", label: "Societies", icon: Building2, superAdminOnly: true },
  { to: "/forms", label: "Forms catalog", icon: FileText },
  { to: "/analytics", label: "Analytics", icon: BarChart3 },
  { to: "/audit-log", label: "Audit log", icon: ShieldCheck },
  { to: "/settings", label: "Settings", icon: Settings },
];
