/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorRouteImport } from './routes/visitor'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as UtilityMetersRouteImport } from './routes/utility-meters'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PropertyRouteImport } from './routes/property'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as ModulesAdminRouteImport } from './routes/modules-admin'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as ModulesModuleRouteImport } from './routes/modules.$module'
import { Route as FormsModuleFormRouteImport } from './routes/forms.$module.$form'

const VisitorRoute = VisitorRouteImport.update({
  id: '/visitor',
  path: '/visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityMetersRoute = UtilityMetersRouteImport.update({
  id: '/utility-meters',
  path: '/utility-meters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRoute = PropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesAdminRoute = ModulesAdminRouteImport.update({
  id: '/modules-admin',
  path: '/modules-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const ModulesModuleRoute = ModulesModuleRouteImport.update({
  id: '/modules/$module',
  path: '/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsModuleFormRoute = FormsModuleFormRouteImport.update({
  id: '/$module/$form',
  path: '/$module/$form',
  getParentRoute: () => FormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/complaints': typeof ComplaintsRoute
  '/documents': typeof DocumentsRoute
  '/events': typeof EventsRoute
  '/forms': typeof FormsRouteWithChildren
  '/forum': typeof ForumRoute
  '/governance': typeof GovernanceRoute
  '/ledger': typeof LedgerRoute
  '/maintenance': typeof MaintenanceRoute
  '/modules-admin': typeof ModulesAdminRoute
  '/notices': typeof NoticesRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/polls': typeof PollsRoute
  '/property': typeof PropertyRoute
  '/reports': typeof ReportsRoute
  '/residents': typeof ResidentsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/utility-meters': typeof UtilityMetersRoute
  '/vendors': typeof VendorsRoute
  '/visitor': typeof VisitorRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/forms/': typeof FormsIndexRoute
  '/forms/$module/$form': typeof FormsModuleFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/complaints': typeof ComplaintsRoute
  '/documents': typeof DocumentsRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRoute
  '/governance': typeof GovernanceRoute
  '/ledger': typeof LedgerRoute
  '/maintenance': typeof MaintenanceRoute
  '/modules-admin': typeof ModulesAdminRoute
  '/notices': typeof NoticesRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/polls': typeof PollsRoute
  '/property': typeof PropertyRoute
  '/reports': typeof ReportsRoute
  '/residents': typeof ResidentsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/utility-meters': typeof UtilityMetersRoute
  '/vendors': typeof VendorsRoute
  '/visitor': typeof VisitorRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/forms': typeof FormsIndexRoute
  '/forms/$module/$form': typeof FormsModuleFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/complaints': typeof ComplaintsRoute
  '/documents': typeof DocumentsRoute
  '/events': typeof EventsRoute
  '/forms': typeof FormsRouteWithChildren
  '/forum': typeof ForumRoute
  '/governance': typeof GovernanceRoute
  '/ledger': typeof LedgerRoute
  '/maintenance': typeof MaintenanceRoute
  '/modules-admin': typeof ModulesAdminRoute
  '/notices': typeof NoticesRoute
  '/notifications': typeof NotificationsRoute
  '/parking': typeof ParkingRoute
  '/payments': typeof PaymentsRoute
  '/polls': typeof PollsRoute
  '/property': typeof PropertyRoute
  '/reports': typeof ReportsRoute
  '/residents': typeof ResidentsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/utility-meters': typeof UtilityMetersRoute
  '/vendors': typeof VendorsRoute
  '/visitor': typeof VisitorRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/forms/': typeof FormsIndexRoute
  '/forms/$module/$form': typeof FormsModuleFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amenities'
    | '/analytics'
    | '/assets'
    | '/audit-log'
    | '/auth'
    | '/budget'
    | '/complaints'
    | '/documents'
    | '/events'
    | '/forms'
    | '/forum'
    | '/governance'
    | '/ledger'
    | '/maintenance'
    | '/modules-admin'
    | '/notices'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/polls'
    | '/property'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/utility-meters'
    | '/vendors'
    | '/visitor'
    | '/modules/$module'
    | '/forms/'
    | '/forms/$module/$form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amenities'
    | '/analytics'
    | '/assets'
    | '/audit-log'
    | '/auth'
    | '/budget'
    | '/complaints'
    | '/documents'
    | '/events'
    | '/forum'
    | '/governance'
    | '/ledger'
    | '/maintenance'
    | '/modules-admin'
    | '/notices'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/polls'
    | '/property'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/utility-meters'
    | '/vendors'
    | '/visitor'
    | '/modules/$module'
    | '/forms'
    | '/forms/$module/$form'
  id:
    | '__root__'
    | '/'
    | '/amenities'
    | '/analytics'
    | '/assets'
    | '/audit-log'
    | '/auth'
    | '/budget'
    | '/complaints'
    | '/documents'
    | '/events'
    | '/forms'
    | '/forum'
    | '/governance'
    | '/ledger'
    | '/maintenance'
    | '/modules-admin'
    | '/notices'
    | '/notifications'
    | '/parking'
    | '/payments'
    | '/polls'
    | '/property'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/utility-meters'
    | '/vendors'
    | '/visitor'
    | '/modules/$module'
    | '/forms/'
    | '/forms/$module/$form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmenitiesRoute: typeof AmenitiesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  BudgetRoute: typeof BudgetRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DocumentsRoute: typeof DocumentsRoute
  EventsRoute: typeof EventsRoute
  FormsRoute: typeof FormsRouteWithChildren
  ForumRoute: typeof ForumRoute
  GovernanceRoute: typeof GovernanceRoute
  LedgerRoute: typeof LedgerRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ModulesAdminRoute: typeof ModulesAdminRoute
  NoticesRoute: typeof NoticesRoute
  NotificationsRoute: typeof NotificationsRoute
  ParkingRoute: typeof ParkingRoute
  PaymentsRoute: typeof PaymentsRoute
  PollsRoute: typeof PollsRoute
  PropertyRoute: typeof PropertyRoute
  ReportsRoute: typeof ReportsRoute
  ResidentsRoute: typeof ResidentsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  UtilityMetersRoute: typeof UtilityMetersRoute
  VendorsRoute: typeof VendorsRoute
  VisitorRoute: typeof VisitorRoute
  ModulesModuleRoute: typeof ModulesModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitor': {
      id: '/visitor'
      path: '/visitor'
      fullPath: '/visitor'
      preLoaderRoute: typeof VisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility-meters': {
      id: '/utility-meters'
      path: '/utility-meters'
      fullPath: '/utility-meters'
      preLoaderRoute: typeof UtilityMetersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property': {
      id: '/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof PropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules-admin': {
      id: '/modules-admin'
      path: '/modules-admin'
      fullPath: '/modules-admin'
      preLoaderRoute: typeof ModulesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/modules/$module': {
      id: '/modules/$module'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof ModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$module/$form': {
      id: '/forms/$module/$form'
      path: '/$module/$form'
      fullPath: '/forms/$module/$form'
      preLoaderRoute: typeof FormsModuleFormRouteImport
      parentRoute: typeof FormsRoute
    }
  }
}

interface FormsRouteChildren {
  FormsIndexRoute: typeof FormsIndexRoute
  FormsModuleFormRoute: typeof FormsModuleFormRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsIndexRoute: FormsIndexRoute,
  FormsModuleFormRoute: FormsModuleFormRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmenitiesRoute: AmenitiesRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssetsRoute: AssetsRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  BudgetRoute: BudgetRoute,
  ComplaintsRoute: ComplaintsRoute,
  DocumentsRoute: DocumentsRoute,
  EventsRoute: EventsRoute,
  FormsRoute: FormsRouteWithChildren,
  ForumRoute: ForumRoute,
  GovernanceRoute: GovernanceRoute,
  LedgerRoute: LedgerRoute,
  MaintenanceRoute: MaintenanceRoute,
  ModulesAdminRoute: ModulesAdminRoute,
  NoticesRoute: NoticesRoute,
  NotificationsRoute: NotificationsRoute,
  ParkingRoute: ParkingRoute,
  PaymentsRoute: PaymentsRoute,
  PollsRoute: PollsRoute,
  PropertyRoute: PropertyRoute,
  ReportsRoute: ReportsRoute,
  ResidentsRoute: ResidentsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  UtilityMetersRoute: UtilityMetersRoute,
  VendorsRoute: VendorsRoute,
  VisitorRoute: VisitorRoute,
  ModulesModuleRoute: ModulesModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
